language: python
notifications:
  email: false

jobs:
  include:
    # LINUX MACHINE #
    - name: " Python 3.6 Linux "
      python: 3.6

    - name: " Python 3.7 Linux "
      python: 3.7

    # macOSx MACHINE #
    - name: " Python 3.6.5 macOSx 10.13"
      os: osx
      osx_image: xcode10.13 # Python 3.6.5 running on macOS 10.13
      language: shell     # 'language python' is an error on Travis CI macOs

    - name: " Python 3.7.3 macOSx 10.14"
      os: osx
      osx_image: xcode11 # Python 3.7.3 runnning on macOsx 10.14
      language: shell      # 'language python' is an error on Travis CI macOs

# command to install dependencies
install:
  - python3 --version
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install -r tests/requirements.txt

before_script:
  - black --version && black --check poisson_solver tests
  - flake8 --version && flake8 poisson_solver tests

# command to run tests
script:
  - python3 -m pytest --cov=poisson_solver --cov-report=xml

after_success:
  - coverage report
  - codecov -t "${CODECOV_TOKEN}"
  - coveralls
  # - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
  #     bash <(curl -s https://codecov.io/bash)
  #     # codecov;
  #   fi
